<?php
	/** @var FreshRSS_View $this */
	$this->partial('aside_configure');
?>

<main class="post">
<h1>YouTube Takeout import</h1>
<form action="<?php echo _url('yttakeout', 'import'); ?>" method="POST" enctype="multipart/form-data">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>">

	<div class="form-group">
		<label class="group-name" for="name">New category name:</label>
		<div class="group-controls">
			<input type="text" id="name" name="name">
		</div>
	</div>

	<div class="form-group">
		<label class="group-name" for="subscriptions_csv">Takeout's <code>subscriptions.csv</code>:</label>
		<div class="group-controls">
			<input type="file" id="subscriptions_csv" name="subscriptions_csv">
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important">Import</button>
		</div>
	</div>
</form>

</main>