<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="POST">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>">

	<div class="form-group">
		<label class="group-name" for="nitter_instance">Instance URL:</label>
		<div class="group-controls">
			<input type="text" id="nitter_instance" name="instance" value="<?php echo FreshRSS_Context::$user_conf->nitter_instance; ?>" data-leave-validation="1">
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important">Save</button>
		</div>
	</div>
</form>
